// Generated by CoffeeScript 1.12.7
(function() {
  var config, exports;

  exports = exports != null ? exports : this;

  config = {
    demoMode: true,
    server: {
      addr: '0.0.0.0',
      port: process.env.port || 8089,
      prefix: '/pong'
    },
    client: {
      interpolate: false,
      regularLinearInterpolate: false,
      optimizedLinearInterpolate: false,
      interpLatency: 100
    },
    update: {
      interval: 20,
      syncTime: 40,
      maxDrift: 100,
      timerAccuracy: 5
    },
    board: {
      id: 'board',
      size: {
        x: 500,
        y: 300
      }
    },
    block: {
      size: {
        x: 8,
        y: 100
      },
      colors: ['blue', 'red'],
      names: ['left', 'right'],
      velocity: 0.08
    },
    ball: {
      radius: 6,
      xVelocity: 0.4,
      yVelocity: 0.15,
      color: 'black',
      accelerationFromPaddle: 0.05
    },
    messageBoard: {
      id: 'message_board'
    },
    scoreBoard: {
      id: 'score_board'
    }
  };

  config.client.maxInterp = config.ball.radius * 5;

  exports.WebPongJSConfig = config;

}).call(this);
